apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-manual
spec:
  suspend: True
  schedule: '* * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-manual
              image: {{ .Values.images.graphdb }}
              volumeMounts:
                - name: graphdb-utils
                  mountPath: /tmp/utils
              command: ['bash',
                        '-c',
                        'cp /tmp/utils/backup.sh /usr/local/bin/; chmod +x /usr/local/bin/backup.sh; /usr/local/bin/backup.sh "{{.Values.graphdb.masters.repository}}" >> /proc/1/fd/1']
          restartPolicy: Never
          volumes:
            - name: graphdb-utils
              configMap:
                name: graphdb-utils-configmap