apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: run-script-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: run-script-manual-backup
              image: {{ .Values.images.graphdb }}
              volumeMounts:
                - name: graphdb-utils
                  mountPath: /tmp/utils
              command: ['bash',
                        '-c',
                        'cp /tmp/utils/runManualBackup.sh /tmp/utils/backup.sh /usr/local/bin/; chmod +x /usr/local/bin/runManualBackup.sh; chmod +x /usr/local/bin/backup.sh; /usr/local/bin/runManualBackup.sh "{{.Values.graphdb.backupRestore.trigger_backup}}" "{{.Values.graphdb.masters.repository}}" >> /proc/1/fd/1']
          restartPolicy: Never
          volumes:
            - name: graphdb-utils
              configMap:
                name: graphdb-utils-configmap
