# Default configuration map for provisioning GraphDB repository.
# To change it, prepare another configuration map and update "graphdb.repositoryConfigmap"
{{- $configs := (.Values.graphdb.configs | default dict) }}
{{- $usersConfigMap := $configs.usersConfigMap | default "null"}}
{{- if or (eq $usersConfigMap "graphdb-users-configmap") (and (eq $usersConfigMap "null") (.Values.graphdb.security.enabled)) }}
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: graphdb-users-configmap
  labels:
    name: graphdb-users-configmap
data:
  users.js: |-
{{ tpl (.Files.Get "files/config/users.js" | indent 4) . }}
{{- end }}
