# Default configuration map for provisioning GraphDB logback settings.
# To change it, prepare another configuration map and update "graphdb.configs.logbackConfigMap"
{{- $configs := (.Values.graphdb.configs | default dict) }}
{{- if $configs.logbackConfigMap }}
{{- if eq $configs.logbackConfigMap "graphdb-logback-configmap" }}
apiVersion: {{ .Values.versions.configmap }}
kind: ConfigMap
metadata:
  name: graphdb-logback-configmap
  labels:
    name: graphdb-logback-configmap
data:
  logback.xml: |-
{{ tpl (.Files.Get "files/config/logback.xml" | indent 4) . }}
{{- end }}
{{- end }}
