apiVersion: {{ $.Values.versions.pv }}
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: {{ $.Values.deployment.storage }}/graphdb-backups

