apiVersion: {{ $.Values.versions.pvc }}
kind: PersistentVolumeClaim
metadata:
  name: graphdb-worker-preload-data-pvc
  labels:
    name: graphdb-worker-preload-data-pvc
spec:
  volumeName: {{ $.Release.Namespace }}-graphdb-worker-default-worker-preload-data-pv
  storageClassName: {{ $.Values.graphdb.tools.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.graphdb.masters.persistence.storage }}
