
{{ if eq .Values.graphdb.masters.persistence.volumeNamePrefix "graphdb-master-default" }}
{{ range $i, $master_index := untilStep 1 (add1 $.Values.graphdb.clusterConfig.mastersCount | int ) 1 }}
#
# Default persistence volume for GraphDB workers. Data is stored on the node file system. Suitable
# for Minikube deployments.
#
# Note: Not to be used in production or multi node cluster.
#
---
apiVersion: {{ $.Values.versions.pv }}
kind: PersistentVolume
metadata:
  name: graphdb-master-default-master-{{ $master_index }}-pv
  labels:
    name: graphdb-master-default-master-{{ $master_index }}-pv
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ $.Values.graphdb.masters.persistence.storage }}
  hostPath:
    path: {{ $.Values.deployment.storage }}/graphdb-master-{{ $master_index }}-data

{{ end }}
{{ end }}
