{{ if ne .Values.graphdb.topology "standalone" }}
{{ range $i, $worker_index := untilStep 1 (add1 $.Values.graphdb.clusterConfig.workersCount | int ) 1 }}

---
apiVersion: {{ $.Values.versions.pvc }}
kind: PersistentVolumeClaim
metadata:
  name: graphdb-worker-{{ $worker_index }}-data-pvc
  labels:
    name: graphdb-worker-{{ $worker_index }}-data-pvc
spec:
  {{- if $.Values.graphdb.workers.persistence.volumeNamePrefix }}
  volumeName: {{ $.Release.Namespace }}-{{ $.Values.graphdb.workers.persistence.volumeNamePrefix }}-{{$worker_index}}-pv
  {{- end }}
  storageClassName: {{ $.Values.graphdb.workers.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.graphdb.workers.persistence.storage }}

{{ end }}
{{ end }}
