{{ range $i, $master_index := untilStep 1 (add1 $.Values.graphdb.mastersCount | int ) 1 }}
---
apiVersion: {{ $.Values.versions.pvc }}
kind: PersistentVolumeClaim
metadata:
  name: graphdb-master-{{ $master_index }}-data-pvc
  labels:
    name: graphdb-master-{{ $master_index }}-data-pvc
spec:
  volumeName:  {{ $.Values.graphdb.masters.persistence.volumeNamePrefix }}-master-{{$master_index}}-pv
  storageClassName: {{ $.Values.graphdb.masters.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.graphdb.masters.persistence.storage }}
{{ end }}
